### ISSUE TITLE
copl.yaml to. configure ephemeral env timeout

### ISSUE THREAD

**Issue by YuceS** [commandplaneio/copl#3]
I want the environment TTL to be configurable from[ copl.yaml](https://github.com/commandplaneio/copl/blob/main/config/copl.yaml) file.

This will allow developer to decide the length of the environment duration.

**Comment by commandplaneio** [comment]
[the configuration item](https://github.com/commandplaneio/copl/blob/f0941af40780bfc1cd2ded1987ef0bd511c9195c/config/copl.yaml#L8)
