### ISSUE TITLE
copl.yaml to configure the instance type

### ISSUE THREAD

**Issue by YuceS** [commandplaneio/copl#4]
I want the instance size  to be configurable from[ copl.yaml](https://github.com/commandplaneio/copl/blob/main/config/copl.yaml) file.

This will allow developer to decide the size of the environment.

**Comment by commandplaneio** [comment]
[The configuration item](https://github.com/commandplaneio/copl/blob/f0941af40780bfc1cd2ded1987ef0bd511c9195c/config/copl.yaml#L13)
